apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: prometheus-ui
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prometheus.dev.example.com  # Replace with dev-specific domain
