server:
  enabled: true
  service:
    type: ClusterIP
    port: 9090
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: standard # Replace with your cluster's storage class

alertmanager:
  enabled: false # Disable Alertmanager if not required

pushgateway:
  enabled: false # Disable Pushgateway if not required

# Customize retention policy
prometheusSpec:
  retention: 15d
  scrapeInterval: 15s
